AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  geonorm-api
  La infraestructura para la API de normalización de direcciones GeoNorm.

Globals:
  Function:
    Timeout: 15
    MemorySize: 256
    Runtime: python3.12
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  GeoNormApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: api.app.handler
      Description: Función principal que contiene la lógica de la API GeoNorm.
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Path: /{proxy+} 
            Method: ANY
            Auth:
              ApiKeyRequired: true

      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: GeoNormAPI
          POWERTOOLS_METRICS_NAMESPACE: GeoNorm
          LOG_LEVEL: INFO
      Tags:
        Project: GeoNorm
        Service: CoreAPI

Outputs:
  GeoNormApiEndpoint:
    Description: "URL del API Gateway para el entorno de producción"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  GeoNormApiFunctionArn:
    Description: "ARN de la función Lambda principal"
    Value: !GetAtt GeoNormApiFunction.Arn