AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  geonorm-api
  La infraestructura para la API de normalización de direcciones GeoNorm.

Globals:
  Function:
    Timeout: 15
    MemorySize: 256
    Runtime: python3.12
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  # --- 1. SE CREA UN RECURSO EXPLÍCITO PARA LA API ---
  # En lugar de una configuración global, definimos la API como su propio recurso.
  GeoNormHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      # Aquí van las configuraciones que antes estaban en el bloque global.
      Auth:
        DefaultAuthorizer:
          ApiKeyRequired: true
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowHeaders: ["*"]
        AllowMethods: ["GET", "POST", "OPTIONS"]

  # --- 2. LA FUNCIÓN LAMBDA SE MANTIENE, PERO SU EVENTO CAMBIA ---
  GeoNormApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: api.app.handler
      Description: Función principal que contiene la lógica de la API GeoNorm.
      Architectures:
        - x86_64
      Events:
        # --- 3. EL EVENTO AHORA SE VINCULA A LA API EXPLÍCITA ---
        # En lugar de definir un proxy genérico, le decimos que responda a cualquier
        # petición en la API que creamos arriba ('GeoNormHttpApi').
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+} # Un "catch-all" para que FastAPI maneje las rutas
            Method: ANY
            ApiId: !Ref GeoNormHttpApi # ¡Este es el vínculo clave!

      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: GeoNormAPI
          POWERTOOLS_METRICS_NAMESPACE: GeoNorm
          LOG_LEVEL: INFO
      Tags:
        Project: GeoNorm
        Service: CoreAPI

Outputs:
  # --- 4. LA SALIDA AHORA TOMA LA URL DIRECTAMENTE DEL RECURSO DE LA API ---
  GeoNormApiEndpoint:
    Description: "URL del API Gateway para el entorno de producción"
    Value: !GetAtt GeoNormHttpApi.ApiEndpoint

  GeoNormApiFunctionArn:
    Description: "ARN de la función Lambda principal"
    Value: !GetAtt GeoNormApiFunction.Arn